apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gcr.io/cyrildiagne-ml/u2net-http
    docker:
      dockerfile: ./Dockerfile
deploy:
  kubectl:
    manifests:
      - deploy/knative.yaml
